-- ─────────────────────────────────────────────────────────────────────────────
-- Canonical country codes.
--
-- board_top filters leaderboard entries with `e.country = p_country`. Two codes
-- meaning one country therefore split a nation across two half-populated
-- boards. Nothing errors and nothing in the app can show which board is real.
--
-- Sixteen codes can do this. `UK` is the important one and it is neither a typo
-- nor a withdrawn code: it is *exceptionally reserved* in ISO 3166-1, CLDR maps
-- it onto the same country as `GB`, and any locale API can produce it. The rest
-- are formerly-used codes with live successors (SU→RU, YU→RS, ZR→CD, DD→DE, …).
--
-- The client canonicalises on every write path (src/data/countries.ts). This
-- migration makes the bad state unrepresentable rather than merely unwritten,
-- so a direct SQL write or a future second client cannot reintroduce it.
--
-- NO-OP SAFE AND IDEMPOTENT. Both environments currently hold only `GB` and
-- nulls, so the canonicalisation pass is expected to report 0 rows changed on
-- its first run. That is the point: a migration that has never run is untested
-- code, and one that reports what it did can be re-run to prove it is stable.
-- Every statement below is guarded, so running this file twice is safe and the
-- second run reports zeroes.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── the canonical set ────────────────────────────────────────────────────────
-- 249 assigned ISO 3166-1 alpha-2 codes plus XK. Generated by
-- scripts/generate-countries.mjs from the CLDR data in Node's ICU; the same
-- 250 rows the picker offers. See src/data/countries.provenance.json for the
-- ICU/CLDR version this was cut from, and the generator for why XK is in and
-- why the reserved codes (AC, TA, EA, IC, CQ, …) are out.

create table if not exists countries (
  code char(2) primary key,
  name text not null
);

comment on table countries is
  'Canonical country codes. Generated by scripts/generate-countries.mjs — do not hand-edit; regenerate and write a migration.';

insert into countries (code, name) values
  ('AF', 'Afghanistan'),
  ('AX', 'Åland Islands'),
  ('AL', 'Albania'),
  ('DZ', 'Algeria'),
  ('AS', 'American Samoa'),
  ('AD', 'Andorra'),
  ('AO', 'Angola'),
  ('AI', 'Anguilla'),
  ('AQ', 'Antarctica'),
  ('AG', 'Antigua & Barbuda'),
  ('AR', 'Argentina'),
  ('AM', 'Armenia'),
  ('AW', 'Aruba'),
  ('AU', 'Australia'),
  ('AT', 'Austria'),
  ('AZ', 'Azerbaijan'),
  ('BS', 'Bahamas'),
  ('BH', 'Bahrain'),
  ('BD', 'Bangladesh'),
  ('BB', 'Barbados'),
  ('BY', 'Belarus'),
  ('BE', 'Belgium'),
  ('BZ', 'Belize'),
  ('BJ', 'Benin'),
  ('BM', 'Bermuda'),
  ('BT', 'Bhutan'),
  ('BO', 'Bolivia'),
  ('BA', 'Bosnia & Herzegovina'),
  ('BW', 'Botswana'),
  ('BV', 'Bouvet Island'),
  ('BR', 'Brazil'),
  ('IO', 'British Indian Ocean Territory'),
  ('VG', 'British Virgin Islands'),
  ('BN', 'Brunei'),
  ('BG', 'Bulgaria'),
  ('BF', 'Burkina Faso'),
  ('BI', 'Burundi'),
  ('KH', 'Cambodia'),
  ('CM', 'Cameroon'),
  ('CA', 'Canada'),
  ('CV', 'Cape Verde'),
  ('BQ', 'Caribbean Netherlands'),
  ('KY', 'Cayman Islands'),
  ('CF', 'Central African Republic'),
  ('TD', 'Chad'),
  ('CL', 'Chile'),
  ('CN', 'China'),
  ('CX', 'Christmas Island'),
  ('CC', 'Cocos (Keeling) Islands'),
  ('CO', 'Colombia'),
  ('KM', 'Comoros'),
  ('CG', 'Congo - Brazzaville'),
  ('CD', 'Congo - Kinshasa'),
  ('CK', 'Cook Islands'),
  ('CR', 'Costa Rica'),
  ('CI', 'Côte d’Ivoire'),
  ('HR', 'Croatia'),
  ('CU', 'Cuba'),
  ('CW', 'Curaçao'),
  ('CY', 'Cyprus'),
  ('CZ', 'Czechia'),
  ('DK', 'Denmark'),
  ('DJ', 'Djibouti'),
  ('DM', 'Dominica'),
  ('DO', 'Dominican Republic'),
  ('EC', 'Ecuador'),
  ('EG', 'Egypt'),
  ('SV', 'El Salvador'),
  ('GQ', 'Equatorial Guinea'),
  ('ER', 'Eritrea'),
  ('EE', 'Estonia'),
  ('SZ', 'Eswatini'),
  ('ET', 'Ethiopia'),
  ('FK', 'Falkland Islands'),
  ('FO', 'Faroe Islands'),
  ('FJ', 'Fiji'),
  ('FI', 'Finland'),
  ('FR', 'France'),
  ('GF', 'French Guiana'),
  ('PF', 'French Polynesia'),
  ('TF', 'French Southern Territories'),
  ('GA', 'Gabon'),
  ('GM', 'Gambia'),
  ('GE', 'Georgia'),
  ('DE', 'Germany'),
  ('GH', 'Ghana'),
  ('GI', 'Gibraltar'),
  ('GR', 'Greece'),
  ('GL', 'Greenland'),
  ('GD', 'Grenada'),
  ('GP', 'Guadeloupe'),
  ('GU', 'Guam'),
  ('GT', 'Guatemala'),
  ('GG', 'Guernsey'),
  ('GN', 'Guinea'),
  ('GW', 'Guinea-Bissau'),
  ('GY', 'Guyana'),
  ('HT', 'Haiti'),
  ('HM', 'Heard & McDonald Islands'),
  ('HN', 'Honduras'),
  ('HK', 'Hong Kong SAR China'),
  ('HU', 'Hungary'),
  ('IS', 'Iceland'),
  ('IN', 'India'),
  ('ID', 'Indonesia'),
  ('IR', 'Iran'),
  ('IQ', 'Iraq'),
  ('IE', 'Ireland'),
  ('IM', 'Isle of Man'),
  ('IL', 'Israel'),
  ('IT', 'Italy'),
  ('JM', 'Jamaica'),
  ('JP', 'Japan'),
  ('JE', 'Jersey'),
  ('JO', 'Jordan'),
  ('KZ', 'Kazakhstan'),
  ('KE', 'Kenya'),
  ('KI', 'Kiribati'),
  ('XK', 'Kosovo'),
  ('KW', 'Kuwait'),
  ('KG', 'Kyrgyzstan'),
  ('LA', 'Laos'),
  ('LV', 'Latvia'),
  ('LB', 'Lebanon'),
  ('LS', 'Lesotho'),
  ('LR', 'Liberia'),
  ('LY', 'Libya'),
  ('LI', 'Liechtenstein'),
  ('LT', 'Lithuania'),
  ('LU', 'Luxembourg'),
  ('MO', 'Macao SAR China'),
  ('MG', 'Madagascar'),
  ('MW', 'Malawi'),
  ('MY', 'Malaysia'),
  ('MV', 'Maldives'),
  ('ML', 'Mali'),
  ('MT', 'Malta'),
  ('MH', 'Marshall Islands'),
  ('MQ', 'Martinique'),
  ('MR', 'Mauritania'),
  ('MU', 'Mauritius'),
  ('YT', 'Mayotte'),
  ('MX', 'Mexico'),
  ('FM', 'Micronesia'),
  ('MD', 'Moldova'),
  ('MC', 'Monaco'),
  ('MN', 'Mongolia'),
  ('ME', 'Montenegro'),
  ('MS', 'Montserrat'),
  ('MA', 'Morocco'),
  ('MZ', 'Mozambique'),
  ('MM', 'Myanmar (Burma)'),
  ('NA', 'Namibia'),
  ('NR', 'Nauru'),
  ('NP', 'Nepal'),
  ('NL', 'Netherlands'),
  ('NC', 'New Caledonia'),
  ('NZ', 'New Zealand'),
  ('NI', 'Nicaragua'),
  ('NE', 'Niger'),
  ('NG', 'Nigeria'),
  ('NU', 'Niue'),
  ('NF', 'Norfolk Island'),
  ('KP', 'North Korea'),
  ('MK', 'North Macedonia'),
  ('MP', 'Northern Mariana Islands'),
  ('NO', 'Norway'),
  ('OM', 'Oman'),
  ('PK', 'Pakistan'),
  ('PW', 'Palau'),
  ('PS', 'Palestinian Territories'),
  ('PA', 'Panama'),
  ('PG', 'Papua New Guinea'),
  ('PY', 'Paraguay'),
  ('PE', 'Peru'),
  ('PH', 'Philippines'),
  ('PN', 'Pitcairn Islands'),
  ('PL', 'Poland'),
  ('PT', 'Portugal'),
  ('PR', 'Puerto Rico'),
  ('QA', 'Qatar'),
  ('RE', 'Réunion'),
  ('RO', 'Romania'),
  ('RU', 'Russia'),
  ('RW', 'Rwanda'),
  ('WS', 'Samoa'),
  ('SM', 'San Marino'),
  ('ST', 'São Tomé & Príncipe'),
  ('SA', 'Saudi Arabia'),
  ('SN', 'Senegal'),
  ('RS', 'Serbia'),
  ('SC', 'Seychelles'),
  ('SL', 'Sierra Leone'),
  ('SG', 'Singapore'),
  ('SX', 'Sint Maarten'),
  ('SK', 'Slovakia'),
  ('SI', 'Slovenia'),
  ('SB', 'Solomon Islands'),
  ('SO', 'Somalia'),
  ('ZA', 'South Africa'),
  ('GS', 'South Georgia & South Sandwich Islands'),
  ('KR', 'South Korea'),
  ('SS', 'South Sudan'),
  ('ES', 'Spain'),
  ('LK', 'Sri Lanka'),
  ('BL', 'St. Barthélemy'),
  ('SH', 'St. Helena'),
  ('KN', 'St. Kitts & Nevis'),
  ('LC', 'St. Lucia'),
  ('MF', 'St. Martin'),
  ('PM', 'St. Pierre & Miquelon'),
  ('VC', 'St. Vincent & Grenadines'),
  ('SD', 'Sudan'),
  ('SR', 'Suriname'),
  ('SJ', 'Svalbard & Jan Mayen'),
  ('SE', 'Sweden'),
  ('CH', 'Switzerland'),
  ('SY', 'Syria'),
  ('TW', 'Taiwan'),
  ('TJ', 'Tajikistan'),
  ('TZ', 'Tanzania'),
  ('TH', 'Thailand'),
  ('TL', 'Timor-Leste'),
  ('TG', 'Togo'),
  ('TK', 'Tokelau'),
  ('TO', 'Tonga'),
  ('TT', 'Trinidad & Tobago'),
  ('TN', 'Tunisia'),
  ('TR', 'Türkiye'),
  ('TM', 'Turkmenistan'),
  ('TC', 'Turks & Caicos Islands'),
  ('TV', 'Tuvalu'),
  ('UM', 'U.S. Outlying Islands'),
  ('VI', 'U.S. Virgin Islands'),
  ('UG', 'Uganda'),
  ('UA', 'Ukraine'),
  ('AE', 'United Arab Emirates'),
  ('GB', 'United Kingdom'),
  ('US', 'United States'),
  ('UY', 'Uruguay'),
  ('UZ', 'Uzbekistan'),
  ('VU', 'Vanuatu'),
  ('VA', 'Vatican City'),
  ('VE', 'Venezuela'),
  ('VN', 'Vietnam'),
  ('WF', 'Wallis & Futuna'),
  ('EH', 'Western Sahara'),
  ('YE', 'Yemen'),
  ('ZM', 'Zambia'),
  ('ZW', 'Zimbabwe')
on conflict (code) do update set name = excluded.name;

-- Reference data: world-readable, service-role writable, same as the boards.
alter table countries enable row level security;
drop policy if exists countries_select on countries;
create policy countries_select on countries for select using (true);
grant select on countries to anon, authenticated;

-- ── canonicalisation pass ────────────────────────────────────────────────────

do $$
declare
  n_profiles int;
  n_entries  int;
  n_payloads int;
begin
  create temp table _alias (from_code char(2) primary key, to_code char(2) not null);
  insert into _alias (from_code, to_code) values
    ('AN', 'CW'),
    ('BU', 'MM'),
    ('CS', 'RS'),
    ('DD', 'DE'),
    ('DY', 'BJ'),
    ('FX', 'FR'),
    ('HV', 'BF'),
    ('NH', 'VU'),
    ('RH', 'ZW'),
    ('SU', 'RU'),
    ('TP', 'TL'),
    ('UK', 'GB'),
    ('VD', 'VN'),
    ('YD', 'YE'),
    ('YU', 'RS'),
    ('ZR', 'CD');

  with u as (
    update profiles p set country = a.to_code
      from _alias a where p.country = a.from_code
      returning 1
  ) select count(*) into n_profiles from u;

  -- Denormalised on purpose: an entry records the country the run was set in,
  -- and must not move when the driver later emigrates. Canonicalising it is a
  -- spelling change, not a re-derivation.
  with u as (
    update leaderboard_entries e set country = a.to_code
      from _alias a where e.country = a.from_code
      returning 1
  ) select count(*) into n_entries from u;

  -- ── achievements.payload->>'country' ──────────────────────────────────────
  -- IN PLACE, and the distinction matters.
  --
  -- This rewrites ZR to CD: the same country, spelled canonically. It does NOT
  -- re-read profiles.country, and must never be changed to.
  --
  -- The payload is written once — grantAchievements upserts with
  -- ignoreDuplicates, so the row is never updated after the first grant — which
  -- makes it a permanent snapshot of where the driver was when they topped that
  -- board, not a cache of where they are now. leaderboard_entries.country is a
  -- snapshot too, so an emigrant's old entries stay put and they may genuinely
  -- still hold that board. Re-deriving from profiles would relabel the badge
  -- "Top of the FR board" for a run set in GB: a badge that lies.
  --
  -- There is deliberately no constraint on this field. It is not an independent
  -- input — achievements grants `insert`/`update`/`delete` to no client role
  -- (RLS on, select-only policy), so the sole writer is verify-drive under the
  -- service role, and it copies the value straight out of profiles.country,
  -- which the foreign key below constrains. The payload inherits that
  -- constraint transitively. Two tests pin the single-writer property, which is
  -- the assumption that argument rests on.
  with u as (
    update achievements ach
      set payload = jsonb_set(ach.payload, '{country}', to_jsonb(a.to_code::text))
      from _alias a where ach.payload->>'country' = a.from_code
      returning 1
  ) select count(*) into n_payloads from u;

  drop table _alias;

  raise notice 'country canonicalisation: profiles=% leaderboard_entries=% achievements.payload=%',
    n_profiles, n_entries, n_payloads;
end $$;

-- ── make the bad state unrepresentable ───────────────────────────────────────
-- Foreign keys rather than CHECK constraints: the valid set is data, so it
-- lives in a table that can be extended by a migration instead of in a
-- constraint body that has to be dropped and rebuilt. Both columns are
-- nullable and stay nullable — "no country set" is a state the app handles
-- everywhere, and is the right answer for a driver who has not chosen one.

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'profiles_country_fkey') then
    alter table profiles
      add constraint profiles_country_fkey foreign key (country) references countries (code);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'leaderboard_entries_country_fkey') then
    alter table leaderboard_entries
      add constraint leaderboard_entries_country_fkey foreign key (country) references countries (code);
  end if;
end $$;
